export { CartIcon } from './cart_Icon'
export { LoginIcon } from './Login_Icon'
export {SearchIcon} from './search_Icon'
export {MagicPenIcon} from './magicpen_icon'
export {BrushIcon} from './brush_icon'
export {MedalStarIcon} from './medal_star'
export {MenuIcon} from './menu_icon'
export {BestSellerBag} from './best_seller_bag'
export {FacebookIcon} from './facebook_icon'
export {InstagramIcon} from './instagram_icon'
export {LinkedinIcon} from './linkedin_icon'
export {PinterestIcon} from './pinterest_icon'
export {DiscountIcon} from './discount_Icon'